### ISSUE TITLE
5.1 audio track not found

### ISSUE THREAD

**Issue by anaveem** [jangxx/netflix-1080p#16]
To those users who used this extension 5 months ago or even earlier: did you ever manage to get 5.1 audio? I get good video but it never finds the DD 5.1 audio. Please comment if you are getting 5.1 and give an example of a title. 

Also, I believe the instructions for using this extension were never provided. Shortcuts like Ctrl+Alt+Shift+D / S  for example were never mentioned. If this is by design to keep it hush, I understand. If not, it would be nice if someone could point me to the full documentation about these commands. 

thanks

**Comment by jangxx** [comment]
I am getting 5.1 audio tracks on Netflix's Daredevil for example.

The two shortcuts you mentioned are all the shortcuts that this extension adds. They are not explicitly mentioned anywhere, because they have been part of the Netflix player for many years already with loads of articles written about them. Only in 2018 did Netflix remove them from the player and since this extension only re-enables them (it doesn't add anything new), I don't see a reason to advertise them. I could maybe add a "features" section to the readme however, where I would then list "re-enables removed keyboard shortcuts" among other features this extension has.

**Comment by anaveem** [comment]
Thanks for the quick reply. 
Also, I believe there is another shortcut: Ctrl+Alt+Shift+L to bring up network activity.

I just tried Daredevil Ep1, and I'm not getting 5.1. See screenshot below. Do you mind posting a screenshot of what yours looks like? And are you using the latest Chrome? I'm using a version from Oct 2020 in order to keep certain extensions working, but seeing as this was originally developed in 2019, I don't see why it wouldn't work the same in mine.

![1](https://user-images.githubusercontent.com/80137125/111504220-d27ada00-871d-11eb-9ada-55ba9bb5c08e.jpg)

**Comment by jangxx** [comment]
Your screenshot explicitly says

>Audio Track: en, Id: A:1:1;6;en;1;, Channels: 5.1, Codec: audio/mp4; codecs="mp4a.40.5"

Where exactly are you getting the idea from, that you are not getting 5.1 audio?

**Comment by anaveem** [comment]
I am looking at "playing bitrate" and it's showing 192. Also the pop up box shows the same. 
I believe the Audio track info is just showing what you have selected, not the actual bitrate you're receiving.

**Comment by jangxx** [comment]
Well yea, the audio bitrate on Netflix is always pretty low, but it's entirely possible to encode a 5.1 audio stream with 192 kbps. I'm actually interested in what you _expect_ to see, because to me everything looks fine.

**Comment by anaveem** [comment]
To put it simply: if the extension is in fact able to unlock 5.1 audio, then I should be able to get the URL for the 5.1 audio track. In other words, if I downloaded the audio track, it would be something like 640kbps DD5.1, not 192kbps.

**Comment by jangxx** [comment]
So I googled for 5 seconds and found [this article](https://www.hiresaudio.online/netflix-quadruples-audio-bit-rate/) that states that 5.1 audio _can_ be encoded with 192 kbps.

Apparently it is possible to get 640 kbps audio from Netflix, but to me it looks like this is only available with different browsers (i.e. DRM schemes that Chrome doesn't support), since Netflix does not want to deliver high bitrate audio to Chrome. It's probably the same issue that causes some title to only play in 540p; If Netflix doesn't encode their media files for certain DRM schemes that Chrome supports, then there is nothing this extension can do about it.

**Comment by anaveem** [comment]
Hmm, you're right; I downloaded the audio track and it has 6 channels. I've never seen 5.1 audio in 192 bitrate. Usually it's 640 (128kbps per channel). Let's just say that there are methods to get 640 but probably not using this extension, unfortunately.
